linkwarden/linkwarden

.dockerignore, .github/workflows/build_images.yml, .gitignore, Dockerfile, Dockerfile.prod, api/Dockerfile, api/config.js, api/modules/getData.js, api/package-lock.json, api/package.json, api/security/chrome.json, api/server.js, docker-compose.yml, src/App.js, src/componets/ViewArchived.js, src/config.js, src/modules/deleteEntity.js, src/modules/send.js
Hi Daniel,
there are a lot of changes here:
- The `docker-compose.yml` is geared for local development.
- The Dockerfile.prod in the root directory gets built and published to Docker Hub whenever you push to master.
- The Dockerfile in the api/ directory gets built and published to Docker Hub whenever you push to master.
- There is a new workflow in the `.github/` directory that does these actions. You must configure `DOCKER_HUB_PASSWORD` and `DOCKER_HUB_USERNAME` secrets in your project settings for this to work.
- I rejigged your config setup to work with Docker and its use of environment variables.
Let me know if you want to meet up on this and we can go over it together.
=> Dockerize the app

Dockerfile
This is a redo of the once lost PR from literally two hours ago.
See #6 for the details.
=> Add support for different Docker versions

.gitignore, lib/api/controllers/links/getLinks.ts, lib/api/controllers/links/postLink.ts, lib/api/controllers/users/getUsers.ts, lib/api/controllers/users/updateUser.ts, pages/api/avatar/[id].ts, prisma/schema.prisma, types/global.ts
I added sqlite compatibility, SQLite doesn't have compatibility for array of primitives so instead whitelistedNames had to be done in a separated table to be able to use them as an array of them.
Also added some files on gitignore, only model whitelistedUser was added to the DB nothing else was moved except some decorators of text typings because SQLite doesn't take them.
Finally a bug fixed causing to spin infinitely on the UI when you add a link and add whitespace or write on the search bar of collection, and send the link it will trigger a bug because whitespace or null was sent in the request body and will try to trim that and will throw an error
=> add sqlite compatibility + fix whitespace bug collections

.github/workflows/release-container.yml
=> chore(builds) Enable arm64 builds

components/Sidebar.tsx, components/SidebarHighlightLink.tsx
this pr require #349 to be merge
=> Sidebar highlight link

components/Navbar.tsx, components/ToggleDarkMode.tsx, pages/_app.tsx, pages/collections/[id].tsx, pages/dashboard.tsx, pages/settings/appearance.tsx, store/localSettings.ts, tailwind.config.js
This update allows for global theme changes addressing #214. Currently, all themes use the same accent, neutral, base, etc. but they only need to be updated in the tailwind config if they are going to changed/used globally.
=> Global theming support

components/LinkViews/LinkComponents/LinkActions.tsx, lib/api/controllers/links/linkId/updateLinkById.ts
Probably want to double check the prisma query is okay ~ I'm relatively new to prisma.
Closes #334
=> feat(collections): Allow a contributor to pin a link from a collection to their dashboard

components/LinkViews/LinkCard.tsx, components/LinkViews/LinkGrid.tsx, components/LinkViews/LinkList.tsx, lib/api/controllers/users/userId/updateUserById.ts, lib/client/generateHrefBasedOnUserPreference .ts, lib/client/generateLinkHref.ts, lib/shared/getArchiveValidity.ts, pages/settings/preference.tsx
=> feat(links): Allow users to choose what happens when they click a link

lib/api/controllers/collections/postCollection.ts, pages/collections/[id].tsx, pages/links/index.tsx, pages/links/pinned.tsx, pages/tags/[id].tsx
After deleting all links with the bulk action the buttons would still be visible:
=> fix(links): Bulk deleting all links still showing buttons

components/LinkViews/Layouts/MasonryView.tsx, components/LinkViews/LinkCard.tsx, components/ViewDropdown.tsx, package.json, pages/api/v1/auth/[...nextauth].ts, pages/api/v1/logins/index.ts, pages/collections/[id].tsx, pages/dashboard.tsx, pages/links/index.tsx, pages/links/pinned.tsx, pages/public/collections/[id].tsx, pages/search.tsx, pages/tags/[id].tsx, types/enviornment.d.ts, types/global.ts, yarn.lock
Adds a masonry view to eliminate unused spaces
=> feat(links): Added Masonry View

pages/search.tsx
Adds bulk actions to the search page to close #559
=> fix(links): Show bulk actions on search page

components/LinkViews/LinkCard.tsx, components/LinkViews/LinkComponents/LinkActions.tsx, components/ReadableView.tsx
This adds the link actions to the link banner in the Readable view so you can update/delete it from the Readable page.
=> Add link actions to readable view

pages/collections/index.tsx
=> Add new collection drop down

Dockerfile
Downside is that the image size is left unchanged...
=> revert dockerfile to working state

lib/api/controllers/migration/importFromHTMLFile.ts, lib/api/controllers/migration/importFromLinkwarden.ts, lib/api/controllers/migration/importFromWallabag.ts
Just delete slice method for url to fix https://github.com/linkwarden/linkwarden/issues/901
Tell me if anything to consider.
=> fix(import): keep url not sliced

.env.sample, lib/api/archiveHandler.ts, lib/api/autoTagLink.ts, package.json, pages/api/v1/config/index.ts
This pull request introduces the Azure AI provider (https://sdk.vercel.ai/providers/ai-sdk-providers/azure).
=> Azure AI provider

lib/api/archiveHandler.ts
Add the ability to specify a remote chrome instance.
To test:
Add the environment variable to the linkwarden container:
```text
PLAYWRIGHT_WS_URL=ws://remote-browser-instance:3001/chrome
```
Update the docker-compose file with the example browserless service, and new env var.
```yaml
version: "3.5"
services:
postgres:
image: postgres:16-alpine
env_file: .env
restart: always
volumes:
- ./pgdata:/var/lib/postgresql/data
linkwarden:
env_file: .env
environment:
- DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
- PLAYWRIGHT_WS_URL=ws://browserless:3001/chrome?blockAds=true
restart: always
image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
ports:
- 3000:3000
volumes:
- ./data:/data/data
depends_on:
- postgres
browserless:
image: …
```
=> Add PLAYWRIGHT_WS_URL to connect to a remote chrome instance

apps/web/components/DashboardLinks.tsx, apps/web/components/LinkViews/LinkComponents/LinkCard.tsx, apps/web/components/LinkViews/LinkComponents/LinkList.tsx, apps/web/components/LinkViews/LinkComponents/LinkMasonry.tsx, apps/web/pages/search.tsx
- Use correct DragNDrop wrapper in the search page
- Fixes issue where dragging link details drawer also triggers drag function
=> fix: properly handle drag-and-drop

apps/web/components/DashboardLayoutDropdown.tsx, apps/web/lib/api/controllers/dashboard/updateDashboardLayout.ts, apps/web/package.json, packages/router/dashboardData.tsx, yarn.lock
This PR fixes the sortable collection list dropdown on the dashboard page.
https://github.com/user-attachments/assets/1dc0189c-ea76-43ff-b5ba-586a798830c2
=> Fix: properly handle collection list on dashboard page

.env.sample, apps/web/pages/api/v1/config/index.ts, apps/worker/lib/archiveHandler.ts, apps/worker/lib/autoTagLink.ts, apps/worker/package.json
Add the perplexity AI provider from the ai-sdk
=> add ai-sdk/perplexity provider
